export interface Wilaya {
  code: string;
  ar: string;
  en: string;
}

// The 58 wilayas of Algeria.
export const WILAYAS: Wilaya[] = [
  { code: "01", ar: "أدرار", en: "Adrar" },
  { code: "02", ar: "الشلف", en: "Chlef" },
  { code: "03", ar: "الأغواط", en: "Laghouat" },
  { code: "04", ar: "أم البواقي", en: "Oum El Bouaghi" },
  { code: "05", ar: "باتنة", en: "Batna" },
  { code: "06", ar: "بجاية", en: "Bejaia" },
  { code: "07", ar: "بسكرة", en: "Biskra" },
  { code: "08", ar: "بشار", en: "Bechar" },
  { code: "09", ar: "البليدة", en: "Blida" },
  { code: "10", ar: "البويرة", en: "Bouira" },
  { code: "11", ar: "تمنراست", en: "Tamanrasset" },
  { code: "12", ar: "تبسة", en: "Tebessa" },
  { code: "13", ar: "تلمسان", en: "Tlemcen" },
  { code: "14", ar: "تيارت", en: "Tiaret" },
  { code: "15", ar: "تيزي وزو", en: "Tizi Ouzou" },
  { code: "16", ar: "الجزائر", en: "Algiers" },
  { code: "17", ar: "الجلفة", en: "Djelfa" },
  { code: "18", ar: "جيجل", en: "Jijel" },
  { code: "19", ar: "سطيف", en: "Setif" },
  { code: "20", ar: "سعيدة", en: "Saida" },
  { code: "21", ar: "سكيكدة", en: "Skikda" },
  { code: "22", ar: "سيدي بلعباس", en: "Sidi Bel Abbes" },
  { code: "23", ar: "عنابة", en: "Annaba" },
  { code: "24", ar: "قالمة", en: "Guelma" },
  { code: "25", ar: "قسنطينة", en: "Constantine" },
  { code: "26", ar: "المدية", en: "Medea" },
  { code: "27", ar: "مستغانم", en: "Mostaganem" },
  { code: "28", ar: "المسيلة", en: "M'Sila" },
  { code: "29", ar: "معسكر", en: "Mascara" },
  { code: "30", ar: "ورقلة", en: "Ouargla" },
  { code: "31", ar: "وهران", en: "Oran" },
  { code: "32", ar: "البيض", en: "El Bayadh" },
  { code: "33", ar: "إليزي", en: "Illizi" },
  { code: "34", ar: "برج بوعريريج", en: "Bordj Bou Arreridj" },
  { code: "35", ar: "بومرداس", en: "Boumerdes" },
  { code: "36", ar: "الطارف", en: "El Tarf" },
  { code: "37", ar: "تندوف", en: "Tindouf" },
  { code: "38", ar: "تيسمسيلت", en: "Tissemsilt" },
  { code: "39", ar: "الوادي", en: "El Oued" },
  { code: "40", ar: "خنشلة", en: "Khenchela" },
  { code: "41", ar: "سوقناس", en: "Souk Ahras" },
  { code: "42", ar: "تيبازة", en: "Tipaza" },
  { code: "43", ar: "ميلة", en: "Mila" },
  { code: "44", ar: "عين الدفلى", en: "Ain Defla" },
  { code: "45", ar: "النعامة", en: "Naama" },
  { code: "46", ar: "عين تموشنت", en: "Ain Temouchent" },
  { code: "47", ar: "غرداية", en: "Ghardaia" },
  { code: "48", ar: "غليزان", en: "Relizane" },
  { code: "49", ar: "تيميمون", en: "Timimoun" },
  { code: "50", ar: "برج باجي مختار", en: "Bordj Badji Mokhtar" },
  { code: "51", ar: "أولاد جلال", en: "Ouled Djellal" },
  { code: "52", ar: "بني عباس", en: "Beni Abbes" },
  { code: "53", ar: "عين صالح", en: "In Salah" },
  { code: "54", ar: "عين قزام", en: "In Guezzam" },
  { code: "55", ar: "تقرت", en: "Touggourt" },
  { code: "56", ar: "جانت", en: "Djanet" },
  { code: "57", ar: "المغير", en: "El M'Ghair" },
  { code: "58", ar: "المنيعة", en: "El Meniaa" },
  { code: "59", ar: "أفلو", en: "Aflou" },
  { code: "60", ar: "بريكة", en: "Barika" },
  { code: "61", ar: "القنطرة", en: "El Kantara" },
  { code: "62", ar: "بئر العاتر", en: "Bir El Ater" },
  { code: "63", ar: "العريشة", en: "El Aricha" },
  { code: "64", ar: "قصر الشلالة", en: "Ksar Chellala" },
  { code: "65", ar: "عين وسارة", en: "Ain Oussera" },
  { code: "66", ar: "مسعد", en: "Messaad" },
  { code: "67", ar: "قصر البخاري", en: "Ksar El Boukhari" },
  { code: "68", ar: "بوسعادة", en: "Bou Saada" },
  { code: "69", ar: "الأبيض سيدي الشيخ", en: "El Abiodh Sidi Cheikh" },
];
