-- ============================================================
-- YR Multicharm - Supabase bootstrap (schema + data)
-- Generated from local dev.db; images repointed to Vercel Blob
-- Run this ONCE in Supabase > SQL Editor > New query > Run
-- ============================================================

BEGIN;

-- clean slate (FK-safe order)
DELETE FROM "CouponProduct";
DELETE FROM "OrderItem";
DELETE FROM "WishlistItem";
DELETE FROM "Review";
DELETE FROM "Order";
DELETE FROM "Address";
DELETE FROM "ProductVariant";
DELETE FROM "Coupon";
DELETE FROM "Product";
DELETE FROM "Category";
DELETE FROM "User";

-- categories
INSERT INTO "Category" ("id","name","slug","icon","createdAt") VALUES ('cmey6cduq0000p8gzjewy1n0a', 'IPL Hair Removal', 'ipl-hair-removal', NULL, NOW());
INSERT INTO "Category" ("id","name","slug","icon","createdAt") VALUES ('cmey6cduq0001p8gzjewy1n0a', 'Beauty Devices', 'beauty-devices', NULL, NOW());
INSERT INTO "Category" ("id","name","slug","icon","createdAt") VALUES ('cmey6cduq0002p8gzjewy1n0a', 'Accessories', 'accessories', NULL, NOW());

-- users (bcrypt hashes preserved - same passwords work)
INSERT INTO "User" ("id","name","email","password","role","phone","createdAt","updatedAt") VALUES ('cmtlpxle40000h4hucl2fi75f', 'Admin', 'admin@glowandbeauty.com', '$2b$12$HcMcuCaCO4VcmL5lO3WvguidQ4vf.zdTCEB9TPp7p15PdsMXTL.pq', 'ADMIN', NULL, '2026-09-03T16:07:25.325Z', '2026-09-03T16:07:25.325Z');
INSERT INTO "User" ("id","name","email","password","role","phone","createdAt","updatedAt") VALUES ('cmtlpxlef0001h4huc9f12ig5', 'Sarah Beauty', 'user@example.com', '$2b$12$ydyiYKTKOCKQrO/o3a6M3erIOc/1CnzhRJUGVtuM1te5dLi2.nesq', 'USER', NULL, '2026-09-03T16:07:25.335Z', '2026-09-03T16:07:25.335Z');

-- products (12)
INSERT INTO "Product" ("id","name","description","price","comparePrice","images","category","subcategory","brand","ingredients","howToUse","stock","isActive","featured","createdAt","updatedAt") VALUES ('cmtlpxlgw000ih4huar282098', 'ANLAN ', 'يتميز بـ 10 مستويات طاقة، و3 أنواع من الأشعة، مع قوة أداء عالية جدًا وجودة تصنيع ممتازة، ليمنحك تجربة استعمال منزلية عملية ومريحة للعناية بالبشرة وتقليل نمو الشعر تدريجيًا.', 68000, NULL, '["https://w4eimkemawe31c3q.public.blob.vercel-storage.com/products/e91eff3b-793f-4ab0-a58c-f87a80344945.jpg"]', 'beauty-devices', 'Hair Removal', 'ANLAN', NULL, 'اختر نوع الشعاع المناسب للمنطقة المراد علاجها. استخدم على البشرة النظيفة والجافة. ابدأ بأدنى مستوى طاقة وزد تدريجياً حسب الراحة.', 40, true, true, '2026-09-03T16:07:25.424Z', '2026-09-03T17:35:54.551Z');
INSERT INTO "Product" ("id","name","description","price","comparePrice","images","category","subcategory","brand","ingredients","howToUse","stock","isActive","featured","createdAt","updatedAt") VALUES ('cmtlpxlfp0006h4hug6pdf9mb', 'Acura 99', 'جهاز IPL منزلي لإزالة الشعر بتقنية الضوء النبضي، مصمم لاستعمال سهل ومريح من المنزل. يحتوي على 999,999 ومضة، مع خاصية التبريد لتجربة ألطف على البشرة، ويأتي مع نظارات حماية وشفرة تحضير للاستعمال العملي. خيار مناسب لمن تبحث عن جهاز اقتصادي وفعال للعناية المنتظمة بالبشرة.', 31000, NULL, '["https://w4eimkemawe31c3q.public.blob.vercel-storage.com/products/acura-99.jpg"]', 'beauty-devices', 'Hair Removal', 'Acura', NULL, 'استخدم الجهاز على البشرة النظيفة والجافة. ابدأ بأدنى مستوى طاقة وزد تدريجياً حسب راحة البشرة. استخدم 2-3 مرات أسبوعياً للحصول على نتائج مثالية.', 50, true, true, '2026-09-03T16:07:25.381Z', '2026-09-03T16:07:25.381Z');
INSERT INTO "Product" ("id","name","description","price","comparePrice","images","category","subcategory","brand","ingredients","howToUse","stock","isActive","featured","createdAt","updatedAt") VALUES ('cmtlpxlhf000oh4hu6mtav5j0', 'Braun Pro 5', 'جهاز IPL منزلي عالي الجودة لإزالة الشعر، مصمم للاستعمال السهل والآمن في المنزل. يحتوي على 400,000 ومضة، 3 درجات طاقة، ويمنحك تجربة عملية ومريحة للعناية المنتظمة بالبشرة، مع نتائج تدريجية لبشرة أنعم مع الاستمرار.', 135000, NULL, '["https://w4eimkemawe31c3q.public.blob.vercel-storage.com/products/7224d1df-1f25-460c-958f-6ae7757b8759.jpg"]', 'ipl-hair-removal', 'Hair Removal', 'Braun', NULL, 'استخدم الجهاز على البشرة النظيفة والجافة. ابدأ بأدنى مستوى طاقة وزد تدريجياً حسب راحة البشرة. استخدم بانتظام للحصول على أفضل النتائج.', 30, true, true, '2026-09-03T16:07:25.443Z', '2026-09-03T17:35:33.514Z');
INSERT INTO "Product" ("id","name","description","price","comparePrice","images","category","subcategory","brand","ingredients","howToUse","stock","isActive","featured","createdAt","updatedAt") VALUES ('cmtlpxlh3000kh4huu4svsc5q', 'DermRays V4S', 'جهاز ليزر منزلي متقدم لإزالة الشعر بتقنية ديود 810 نانومتر، مصمم ليمنحك تجربة عناية العيادة داخل منزلك. يتميز بومضات تلقائية لتسهيل الاستخدام، ونظام تبريد يساعد على جعل الجلسة أكثر راحة. خيار مثالي لمن تبحث عن جهاز قوي، عملي، وعالي الجودة لتقليل نمو الشعر.', 140000, NULL, '["https://w4eimkemawe31c3q.public.blob.vercel-storage.com/products/dermrays-v4s.jpg"]', 'beauty-devices', 'Hair Removal', 'DermRays', NULL, 'استخدم الجهاز على البشرة النظيفة والجافة. ابدأ بأدنى مستوى طاقة وزد تدريجياً. الومضات التلقائية تسهّل الاستخدام والنتيجة تدريجية مع الاستمرار.', 30, true, true, '2026-09-03T16:07:25.431Z', '2026-09-03T16:07:25.431Z');
INSERT INTO "Product" ("id","name","description","price","comparePrice","images","category","subcategory","brand","ingredients","howToUse","stock","isActive","featured","createdAt","updatedAt") VALUES ('cmtlpxlf50002h4hu1ngsevpi', 'IPL 02', 'جهاز ليزر منزلي اقتصادي وعملي لإزالة الشعر، بـ 999,999 ومضة، 5 مستويات طاقة، تبريد عالي، ووضع تلقائي ذكي لراحة أكبر ونتائج تدريجية مع الاستمرار.', 25000, NULL, '["https://w4eimkemawe31c3q.public.blob.vercel-storage.com/products/5193fd14-fd66-4b69-bc9e-e8f9459cd117.jpg","https://w4eimkemawe31c3q.public.blob.vercel-storage.com/products/b6f640f1-68c6-4c1e-acca-ec8d91a5eda2.jpg"]', 'ipl-hair-removal', 'Hair Removal', 'IPL', NULL, 'استخدم الجهاز على البشرة النظيفة والجافة. ابدأ بأدنى مستوى طاقة وزد تدريجياً حسب راحة البشرة. استخدم 2-3 مرات أسبوعياً للحصول على نتائج مثالية.', 50, true, true, '2026-09-03T16:07:25.361Z', '2026-09-03T21:35:29.691Z');
INSERT INTO "Product" ("id","name","description","price","comparePrice","images","category","subcategory","brand","ingredients","howToUse","stock","isActive","featured","createdAt","updatedAt") VALUES ('cmtlpxlfg0004h4huo9g0gz90', 'IPL 03', 'جهاز ليزر منزلي متطور لإزالة الشعر والعناية بالبشرة، يحتوي على 999,999 ومضة، 9 مستويات طاقة، و3 أوضاع ذكية HR / FR / SR للشعر، النضارة، وتحسين مظهر البشرة. مزود بخاصية التبريد ووضع تلقائي ذكي لتجربة أسهل وأكثر راحة، مع نتائج تدريجية لبشرة أنعم مع الاستمرار.', 29500, NULL, '["https://w4eimkemawe31c3q.public.blob.vercel-storage.com/products/IPL-03.jpg"]', 'ipl-hair-removal', 'Hair Removal', 'YR Multicharm', NULL, 'استخدم الجهاز على البشرة النظيفة والجافة. ابدأ بأدنى مستوى طاقة وزد تدريجياً حسب راحة البشرة. استخدم الوضع المناسب حسب المنطقة: HR للشعر، FR للنضارة، SR لتحسين مظهر البشرة.', 50, true, true, '2026-09-03T16:07:25.372Z', '2026-09-03T16:07:25.372Z');
INSERT INTO "Product" ("id","name","description","price","comparePrice","images","category","subcategory","brand","ingredients","howToUse","stock","isActive","featured","createdAt","updatedAt") VALUES ('cmtlpxlgj000eh4huxqrb5fnv', 'KODO', 'جهاز لإزالة الشعر والعناية بالبشرة، من أقوى الأجهزة المنزلية متعددة الاستعمال. يحتوي على 900,000 ومضة، 8 مستويات طاقة، 4 رؤوس مختلفة، وخاصية التبريد لتجربة أكثر راحة. مناسب لتقليل نمو الشعر تدريجياً والعناية بمظهر البشرة من المنزل بطريقة سهلة ومنظمة.', 55000, NULL, '["https://w4eimkemawe31c3q.public.blob.vercel-storage.com/products/kodo.jpg"]', 'beauty-devices', 'Hair Removal', 'KODO', NULL, 'اختر الرأس المناسب للمنطقة المراد علاجها. استخدم على البشرة النظيفة والجافة. ابدأ بأدنى مستوى طاقة وزد تدريجياً. استخدم 2-3 مرات أسبوعياً.', 50, true, true, '2026-09-03T16:07:25.411Z', '2026-09-03T16:07:25.411Z');
INSERT INTO "Product" ("id","name","description","price","comparePrice","images","category","subcategory","brand","ingredients","howToUse","stock","isActive","featured","createdAt","updatedAt") VALUES ('cmtlpxlfw0008h4hurxkaqpvv', 'MLAY T14', 'جهاز منزلي لإزالة الشعر IPL، عملي وسهل الاستعمال، يحتوي على 500,000 ومضة، 5 مستويات طاقة، برمجة أوتوماتيكية وخاصية التبريد لتجربة أكثر راحة. مناسب للعناية المنتظمة من المنزل ويساعد على تقليل نمو الشعر تدريجياً مع الاستمرار.', 35000, NULL, '["https://w4eimkemawe31c3q.public.blob.vercel-storage.com/products/mlay-t14.jpg"]', 'beauty-devices', 'Hair Removal', 'MLAY', NULL, 'استخدم الجهاز على البشرة النظيفة والجافة. ابدأ بأدنى مستوى طاقة وزد تدريجياً حسب راحة البشرة. استخدم 2-3 مرات أسبوعياً للحصول على نتائج مثالية.', 50, true, true, '2026-09-03T16:07:25.388Z', '2026-09-03T16:07:25.388Z');
INSERT INTO "Product" ("id","name","description","price","comparePrice","images","category","subcategory","brand","ingredients","howToUse","stock","isActive","featured","createdAt","updatedAt") VALUES ('cmtlpxlg2000ah4hus8w4ff8p', 'MLAY T16', 'جهاز IPL منزلي لإزالة الشعر، بتصميم عملي وشاشة رقمية سهلة التحكم. يحتوي على 999,999 ومضة، 5 مستويات طاقة، ورأس قابل للتبديل لتجربة استعمال مريحة ومنظمة، يساعد على تقليل نمو الشعر تدريجياً والحصول على بشرة أنعم مع الاستمرار.', 45000, NULL, '["https://w4eimkemawe31c3q.public.blob.vercel-storage.com/products/mlay-t16.jpg"]', 'beauty-devices', 'Hair Removal', 'MLAY', NULL, 'استخدم الجهاز على البشرة النظيفة والجافة. ابدأ بأدنى مستوى طاقة وزد تدريجياً حسب راحة البشرة. استخدم الرأس المناسب حسب المنطقة treatment.', 50, true, true, '2026-09-03T16:07:25.394Z', '2026-09-03T16:07:25.394Z');
INSERT INTO "Product" ("id","name","description","price","comparePrice","images","category","subcategory","brand","ingredients","howToUse","stock","isActive","featured","createdAt","updatedAt") VALUES ('cmtlpxlga000ch4hu212r9216', 'MLAY T18', 'جهاز ليزر منزلي متطور لإزالة الشعر، يتميز بتقنية ذكية تتكيف مع البشرة، 3 درجات قوة، وخاصية التبريد الفوري لتجربة أكثر راحة. تصميمه أنيق وخفيف وسهل الاستعمال، مناسب للعناية المنتظمة في المنزل ويساعد على تقليل نمو الشعر تدريجياً لبشرة أنعم مع الاستمرار.', 39500, NULL, '["https://w4eimkemawe31c3q.public.blob.vercel-storage.com/products/mlay-t18.jpg"]', 'beauty-devices', 'Hair Removal', 'MLAY', NULL, 'استخدم الجهاز على البشرة النظيفة والجافة. التقنية الذكية تتكيف تلقائياً مع لون البشرة. ابدأ بأدنى مستوى وزد تدريجياً حسب الراحة.', 50, true, true, '2026-09-03T16:07:25.402Z', '2026-09-03T16:07:25.402Z');
INSERT INTO "Product" ("id","name","description","price","comparePrice","images","category","subcategory","brand","ingredients","howToUse","stock","isActive","featured","createdAt","updatedAt") VALUES ('cmtlpxlgp000gh4hui11kz13d', 'Philips Lumea', 'جهاز IPL منزلي يحتوي على 450,000 ومضة، 5 مستويات طاقة، ويعمل بالبطارية لحرية استعمال أكبر. مناسب لمن تبحث عن جهاز عملي لبشرة أنعم ونتائج تدريجية مع الاستمرار.', 120000, NULL, '["https://w4eimkemawe31c3q.public.blob.vercel-storage.com/products/philips-lumea.jpg"]', 'ipl-hair-removal', 'Hair Removal', 'Philips', NULL, 'استخدم الجهاز على البشرة النظيفة والجافة. ابدأ بأدنى مستوى طاقة وزد تدريجياً حسب راحة البشرة. يعمل بالبطارية لحرية حركة أكبر أثناء الاستعمال.', 30, true, true, '2026-09-03T16:07:25.417Z', '2026-09-03T16:07:25.417Z');
INSERT INTO "Product" ("id","name","description","price","comparePrice","images","category","subcategory","brand","ingredients","howToUse","stock","isActive","featured","createdAt","updatedAt") VALUES ('cmtlpxlh9000mh4huuwti4yyf', 'Tria Laser 4X', 'جهاز ليزر منزلي بتقنية الديود لإزالة الشعر، مصمم ليمنحك تجربة عناية قريبة من العيادة داخل المنزل. يتميز بقوة أداء عالية، تصميم مريح وسهل الاستخدام، وتقنية احترافية تساعد على تقليل نمو الشعر تدريجياً مع الاستعمال المنتظم. خيار مناسب لمن تبحث عن جهاز قوي وموثوق للعناية بالبشرة والحصول على نعومة تدوم لفترة أطول.', 139000, NULL, '["https://w4eimkemawe31c3q.public.blob.vercel-storage.com/products/tria-4x.jpg"]', 'ipl-hair-removal', 'Hair Removal', 'Tria', NULL, 'استخدم الجهاز على البشرة النظيفة والجافة. ابدأ بأدنى مستوى طاقة وزد تدريجياً. الاستعمال المنتظم يضمن نتائج أفضل ونعومة تدوم.', 30, true, true, '2026-09-03T16:07:25.437Z', '2026-09-03T16:07:25.437Z');

-- product variants (12)
INSERT INTO "ProductVariant" ("id","productId","name","price","stock","sku") VALUES ('cmtlpxlfh0005h4huvjdhwmcr', 'cmtlpxlfg0004h4huo9g0gz90', 'IPL 03', 29500, 50, 'IPL-03-001');
INSERT INTO "ProductVariant" ("id","productId","name","price","stock","sku") VALUES ('cmtlpxlfq0007h4hueob4j13l', 'cmtlpxlfp0006h4hug6pdf9mb', 'Acura 99', 31000, 50, 'ACR-99-001');
INSERT INTO "ProductVariant" ("id","productId","name","price","stock","sku") VALUES ('cmtlpxlfx0009h4huk28eas5x', 'cmtlpxlfw0008h4hurxkaqpvv', 'MLAY T14', 35000, 50, 'MLAY-T14-001');
INSERT INTO "ProductVariant" ("id","productId","name","price","stock","sku") VALUES ('cmtlpxlg4000bh4hurq53z1kh', 'cmtlpxlg2000ah4hus8w4ff8p', 'MLAY T16', 45000, 50, 'MLAY-T16-001');
INSERT INTO "ProductVariant" ("id","productId","name","price","stock","sku") VALUES ('cmtlpxlgb000dh4hue3dvudrn', 'cmtlpxlga000ch4hu212r9216', 'MLAY T18', 39500, 50, 'MLAY-T18-001');
INSERT INTO "ProductVariant" ("id","productId","name","price","stock","sku") VALUES ('cmtlpxlgk000fh4huhe2oi7su', 'cmtlpxlgj000eh4huxqrb5fnv', 'KODO', 55000, 50, 'KODO-001');
INSERT INTO "ProductVariant" ("id","productId","name","price","stock","sku") VALUES ('cmtlpxlgr000hh4hu811fz7fe', 'cmtlpxlgp000gh4hui11kz13d', 'Philips Lumea', 120000, 30, 'PHIL-LUM-001');
INSERT INTO "ProductVariant" ("id","productId","name","price","stock","sku") VALUES ('cmtlpxlh4000lh4huwnvi6sbc', 'cmtlpxlh3000kh4huu4svsc5q', 'DermRays V4S', 140000, 30, 'DERM-V4S-001');
INSERT INTO "ProductVariant" ("id","productId","name","price","stock","sku") VALUES ('cmtlpxlha000nh4hujbyr75xc', 'cmtlpxlh9000mh4huuwti4yyf', 'Tria Laser 4X', 139000, 30, 'TRIA-4X-001');
INSERT INTO "ProductVariant" ("id","productId","name","price","stock","sku") VALUES ('cmtlt2xsn0006xchuwuihlxkq', 'cmtlpxlhf000oh4hu6mtav5j0', 'Braun Pro 5', 135000, 30, 'BRAUN-P5-001');
INSERT INTO "ProductVariant" ("id","productId","name","price","stock","sku") VALUES ('cmtlt3e0z0007xchum10b4r4c', 'cmtlpxlgw000ih4huar282098', 'ANLAN DermRays V4S', 68000, 40, 'ANLAN-V4S-001');
INSERT INTO "ProductVariant" ("id","productId","name","price","stock","sku") VALUES ('cmtm1nhyo0000rohua9vw03pc', 'cmtlpxlf50002h4hu1ngsevpi', 'IPL 02', 25000, 50, 'IPL-02-001');

-- coupons (3)
INSERT INTO "Coupon" ("id","code","discount","type","minAmount","maxUses","usedCount","expiresAt","isActive","createdAt") VALUES ('cmtlpxlhn000qh4huvkzff7kf', 'WELCOME20', 20, 'PERCENTAGE', 30, 100, 5, '2027-12-31T00:00:00.000Z', true, '2026-09-03T16:07:25.451Z');
INSERT INTO "Coupon" ("id","code","discount","type","minAmount","maxUses","usedCount","expiresAt","isActive","createdAt") VALUES ('cmtlpxlhu000rh4hu3yl8hhp5', 'GLOW10', 10, 'PERCENTAGE', NULL, NULL, 12, '2027-06-30T00:00:00.000Z', true, '2026-09-03T16:07:25.458Z');
INSERT INTO "Coupon" ("id","code","discount","type","minAmount","maxUses","usedCount","expiresAt","isActive","createdAt") VALUES ('cmtlpxli1000sh4hub2r8ggnq', 'FREESHIP', 5, 'FIXED', 50, 50, 8, '2027-03-31T00:00:00.000Z', true, '2026-09-03T16:07:25.465Z');

-- coupon<->product links (0)

-- reviews (1)
INSERT INTO "Review" ("id","rating","comment","userId","productId","createdAt") VALUES ('cmtlpxlic000th4huka2865wn', 5, 'جهاز ممتاز ونتائجه واضحة بعد فترة قصيرة. أنصح به بشدة!', 'cmtlpxlef0001h4huc9f12ig5', 'cmtlpxlf50002h4hu1ngsevpi', '2026-09-03T16:07:25.476Z');

COMMIT;

-- verify
SELECT (SELECT count(*) FROM "Product") AS products,
       (SELECT count(*) FROM "Category") AS categories,
       (SELECT count(*) FROM "User") AS users,
       (SELECT count(*) FROM "ProductVariant") AS variants,
       (SELECT count(*) FROM "Coupon") AS coupons;